from enum import Enum, unique

@unique
class CMD_TYPE(Enum):
    TEST = "=?"
    READ = "?"
    WRITE = "="


@unique
class PING(Enum):
    PING_REQUEST = "AT+CIPPING"
    SET_MODE_IP_PACKET_RECEIVE = "AT+CIPCTL"
    SET_RULES_IP_FILTER = "AT+CIPFLT"
    SET_MODULE_PING = "AT+CIPBEIPING"


@unique
class GPRS(Enum):
    ATTACH_DETACH_GPRS_SERVICE = "AT+CGATT"
    DEFINE_PDP_CONTEXT = "AT+CGDCONT"
    QOS_SERVICE_PROFILE_MIN = "AT+CGQMIN"
    QOS_SERVICE_PROFILE_REQUESTED = "AT+CGQREQ"
    PDP_CONTEXT_ACTIVATE_DEACTIVATE = "AT+CGACT"
    ENTER_DATA_STATE = "AT+CGDATA"
    SHOW_PDP_ADDRESS = "AT+CGPADDR"
    GPRS_MOBILE_STATION_CLASS = "AT+CGCLASS"
    CONTROL_UNSOLICITED_GPRS_EVENT_REPORTING = "AT+CGEREP"
    NETWORK_REGISTRATION_STATUS = "AT+CGREG"
    SELECT_SERVICE_MO_SMS = "AT+CGSMS"

